### ISSUE TITLE
A change is coming for overriding the action of ufuncs on records in an Awkward Array

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/vector#12]
It affects this document:

https://vector.readthedocs.io/en/latest/notebooks/VectorDesignPrototype.html

and possibly the implementation. (I haven't searched through the Vector codebase.) While [documenting the way `ak.behavior` works](https://awkward-array.readthedocs.io/en/latest/ak.behavior.html), I changed the expected arguments and return values of the overrides that are defined like this:

```python
ak.behavior[np.equal, "point", "point"] = point_equal
```

such that the function

```python
def point_equal(left, right):
    return np.logical_and(left.x == right.x, left.y == right.y)
```

expects to get `left` and `right` as high-level [ak.Arrays](https://awkward-array.readthedocs.io/en/latest/_auto/ak.Array.html), not low-level [ak.layout.Content](https://awkward-array.readthedocs.io/en/latest/ak.layout.Content.html). (Thus, you can use `.x` and ufuncs like `==` without wrapping and unwrapping.)

This is a better fit to user expectation, since everything else you're doing uses the high-level view. The litmus test is that I forgot this fact while documenting and was surprised when I encountered it: I'm taking that as evidence that it was wrong before.

Numba overrides are unaffected, as is assigning a custom `ak.Array` or `ak.Record` subclass. The only kind of override that actually uses the low-level [ak.layout.Content](https://awkward-array.readthedocs.io/en/latest/ak.layout.Content.html) is custom broadcasting, which is operating at that level anyway, so it should. (That would would _match_ user expectation, for any user advanced enough to be doing it.)

The change is currently in Awkward master; I have _not_ pushed a release yet, though I should do so soon, since a lot of little things have been changed to reflect the documentation.

**Comment by jpivarski** [comment]
That was a long time ago, and it must have either been dealt with or will be when I get to work on the core.

**Comment by henryiii** [comment]
I believe I dealt with it after seeing this issue.

**Comment by jpivarski** [comment]
I'm writing a discussion topic describing what I'll be doing to the `develop` branch so that no one is surprised. You and I talked about it maybe a month ago, and as promised I have some time now in March. What I'll be saying in the Discussion is

   * that I'll be working on the `develop` branch, rather than `main`
   * that I'll be clearing out the `src/vector`, `tests`, and the files (but not `conf.py`, etc.) of `docs`, to "get my head around" what needs to be updated—a lot of that content will likely come back in more or less the same form
   * that I'll be leaving the build and deployment infrastructure (e.g. `setup.cfg` and friends) as it is
   * the general structure of what I'll be writing, which will be largely the same with small changes like the NumPy version being a subclass of `np.ndarray`
   * the order in which I'll be implementing or bringing things back—e.g. the protocols will come back at the end, to make sure nothing's missing
   * I'll cite influences that I'll use for naming conventions: ROOT's LorentzVector, Scikit-HEP's math module, and Coffea's vectors.

I hope to have everything back together again by the end of the month.

**Comment by henryiii** [comment]
I should have time to help very soon now too. I'm coming (slowly) out of being off this week, and boost-histogram is barreling toward 1.0. I'm expecting work on that to be done within a week or so (mostly docs and polish, and some typing). I might focus on Awkward's build system next, so that by the time I'm ready to work on Vector again, things will be back in place.
