### ISSUE TITLE
TVector3 and TVector3Array are missing some important properties

### ISSUE THREAD

**Issue by masonproffitt** [scikit-hep/vector#13]
`TVector3` and `TVector3Array` are missing some important properties that are available for `TLorentzVector`. For example, `eta` and `pt`, which are provided by [ROOT's TVector3](https://root.cern.ch/doc/master/classTVector3.html).

**Comment by jpivarski** [comment]
This library is the future of Lorentz vectors and 3-D vector arrays. Some of these things have names with the momentum associations deliberately removed; for instance, I think that `pt` is more generically `perp`, and the idea is that a momentum subclass would add synonyms like `pt` (to avoid overfilling the namespace with synonyms unless you intend for the vector to be a momentum—what's the `pt` of a secondary vertex?). That might not be the case for `eta`, which is not only a momentum concept, but a momentum-in-hadron-colliders concept. (We never used it in e+ e- colliders.)

**Comment by masonproffitt** [comment]
When is the switch to this library intended, though? I would think this is still something that should be fixed in `uproot_methods` in the meantime.

**Comment by henryiii** [comment]
Roughly in ~1 month. It’s currently held up due to 200% Off my time being devoted to a Ventilator Monitor project, but that’s almost done and about to ship.

**Comment by henryiii** [comment]
This is basically ready to play with, and should have a "ready to try out" release soonish.
