### ISSUE TITLE
Add Jacobian and Polynomial Coordinate Transformation Methods 

### ISSUE THREAD

**Issue by AdvaitDhingra** [scikit-hep/vector#130]
Jacobian's are pretty cool things when it comes to coordinate transformations. This is related to the contravariant transformation PR I made. 

Currently, there is no way to differentiate a function with respect to an arbitrary variable without using SymPy, but maybe there is a way to do this for simple coordinate transformations.

NumPy lets you differentiate a Polynomial Function, so this can be added. For simple cases there is no need to use the Jacobian, instead one can simply use the vector component transformation formula

V'^n = dx'^n / dx^m V^m 

This however wont work for sine and cosine functions and other "non polynomial" coordinate transformations.

**Comment by AdvaitDhingra** [comment]
Nevermind, there is no way to do this without SymPy.

**Comment by jpivarski** [comment]
Derivatives can also be computed with JAX, and both JAX and SymPy would be good backends for Vector. However, adding a backend is a bit of a project, as described in https://github.com/scikit-hep/vector/pull/126#issuecomment-887737304.

**Comment by AdvaitDhingra** [comment]
> Derivatives can also be computed with JAX, and both JAX and SymPy would be good backends for Vector. However, adding a backend is a bit of a project, as described in [#126 (comment)](https://github.com/scikit-hep/vector/pull/126#issuecomment-887737304).

Yeah. I think I'll do some more research before giving this a go
