### ISSUE TITLE
Need coordinate transformation functions with momentum names

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/vector#168]
I just wrote up an example that transformed a Cartesian Lorentz vector into cylindrical coordinate system with pseudorapidity and mass, and I had to say

```python
lorentz_vector.to_rhophietatau()
```

although we had been talking about "pt", "phi", "eta", and "mass" coordinates earlier. What's worse, the Awkward backend makes these the field names. All 12 conversion functions should have momentum-named equivalents that ensure that the output array has momentum field names.

**Comment by matthewfeickert** [comment]
This came up in Discussion #324, and while I assume that there is some non-trivial amount of work for this, it would be quite nice to have.
