### ISSUE TITLE
Add a developer guide specific to `Vector`?

### ISSUE THREAD

**Issue by Saransh-cpp** [scikit-hep/vector#196]
I was wondering if we should add a developer guide specific to vector and link the [Scikit-HEP  developer information](https://scikit-hep.org/developer) within it.

The basic structure of the `.rst` file might look something like this -
- Installing vector
- Activating pre-commit
- Testing vector
- Documenting vector
- The CI/CD pipeline of vector

Should I proceed with this, or should we directly link the Scikit-HEP guide in the documentation?

**Comment by henryiii** [comment]
You can, though I'd start with the template here: https://scikit-hep.org/developer/intro (there's a copy-paste template there).
