### ISSUE TITLE
Add issue and PR templates

### ISSUE THREAD

**Issue by Saransh-cpp** [scikit-hep/vector#237]
`Vector` lacks issue and PR templates, which should be added to make the contribution process smooth for both maintainers and newcomers.

A couple of Scikit-HEP repositories that can be used as inspiration -
- https://github.com/scikit-hep/hist/issues/new/choose
- https://github.com/scikit-hep/pyhf/issues/new/choose

(similarly for PRs)

**Comment by muditchoudhary** [comment]
Hey, @Saransh-cpp would like to work on this? can you assign it to me?

**Comment by Saransh-cpp** [comment]
Oops, I just fixed this. #245 is going stale - you can take up the PR template if the original author does not respond in 2-3 days!

**Comment by muditchoudhary** [comment]
> Oops, I just fixed this. #245 is going stale - you can take up the PR template if the original author does not respond in 2-3 days!

you had made the pr for the pull request template right? so are you talking about the pr template or issue template which I can take? I'm little confused.

**Comment by Saransh-cpp** [comment]
I added issue templates in #267. Right now you can take up #268! (And the PR template one if the original author does not respond)

**Comment by Naman-Priyadarshi** [comment]
I'll work on the PR template feature
