### ISSUE TITLE
Add `CITATION.cff` file

### ISSUE THREAD

**Issue by Saransh-cpp** [scikit-hep/vector#238]
`Vector` recently had its first citation - https://arxiv.org/abs/2205.09137 (citation [138]) - which funnily mentions "T. G. Badger" as an author/co-author/contributor. "T. G. Badger" is [The Gitter Badger](https://github.com/gitter-badger), the Gitter bot.

I think now would be a good time to add a `CITATION` file to `Vector`.

This would require some discussion with the maintainers.

Reference - https://github.com/scikit-hep/scikit-hep.github.io/pull/254
cc: @amangoel185

**Comment by amangoel185** [comment]
Wow, didn't expect that! I agree, a `CITATION.cff` should be pretty simple to add too. [hist/CITATION.cff](https://github.com/scikit-hep/hist/blob/c68a6e6fe90eddc21b82ae758f2f6f992ae35f4b/CITATION.cff) can be used for reference.

**Comment by sdruskat** [comment]
There's also a CFF file generator website (https://citation-file-format.github.io/cff-initializer-javascript/#/) that can hopefully be useful to you in creating the file. As one of the CFF co-leads, I'm happy to be @-mentioned in this issue should there be questions.

(Thanks @danielskatz for the heads up.)
