### ISSUE TITLE
Test with Python `3.10` and set `cancel-in-progress` to `True`

### ISSUE THREAD

**Issue by Saransh-cpp** [scikit-hep/vector#242]
`Vector` supports Python `3.10`, but the support is not tested in the `CI` -
https://github.com/scikit-hep/vector/blob/d4ad49ecf1761e3a6561498d2405b7789d53deff/.github/workflows/ci.yml#L31-L39

---

Additionally, the `cancel-in-progress` field is set to `${{ startsWith(github.ref, 'refs/pull/') }}` -
https://github.com/scikit-hep/vector/blob/d4ad49ecf1761e3a6561498d2405b7789d53deff/.github/workflows/ci.yml#L11-L15
which for some reason returns a `string` now (unverified bug/incorrect documentation, see - https://github.com/github/docs/issues/19416).

I think it should be okay to set it to `true` as set here - https://github.com/scikit-hep/cookie/blob/main/%7B%7Bcookiecutter.project_name%7D%7D/.github/workflows/ci.yml#L18-L20.

**Comment by henryiii** [comment]
Let's add 3.11 too, and do this before release.
