### ISSUE TITLE
Drop Python 2 and 3.5

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/vector#27]
After the smashing success of scikit-hep/boost-histogram#512 (dropping over 400 LOC and cleaning up over 400 more), and the huge implications to typing, etc, I think we should go ahead and drop 2.7/3.5 and make this 3.6+. Some of the features are also potentially quite useful; I'm using the `__init_subclass__` feature right now in boost-histogram to simplify families - see https://github.com/scikit-hep/boost-histogram/pull/513. I think it will reduce development time by at least 20%, CI time similarly, and will promote better typing. I've notices even the LCG is now providing Python 3.8 as the default; and pip, packaging, manylinux2010, and more have dropped 2.7, making it harder to support even if we wanted do. @jpivarski?

**Comment by jpivarski** [comment]
Definitely yes for Python 3.5, and "sure" for Python 2. I was just thinking about that, looking at the type signatures. In the end-state (the end of the month, hopefully), everything will be typed. Those Python 2 type comments don't look very good.

**Comment by henryiii** [comment]
Okay, I can implement that. Feel free to look at all the nice cleanups in https://github.com/scikit-hep/boost-histogram/pull/512 :) And being unable to write variable annotations just is hard to work around with type comments.

**Comment by henryiii** [comment]
Oh, I like the issue number, very easy to remember. :)
