### ISSUE TITLE
Update the "Disassemble Check" test

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/vector#294]
### Vector Version

HEAD

### Python Version

3.8.8

### OS / Environment

GitHub Actions

### Describe the bug

I ran the CI test suite on `main` to make sure that Awkward/Uproot updates aren't breaking anything. (I also made the—unchecked—assumption that CI is testing against Awkward and Uproot pre-releases. I'll have to check that as well.)

Anyway, [the "Disassemble Check" failed](https://github.com/scikit-hep/vector/actions/runs/3634233305/jobs/6132119346). That one was pinned to a Python minor version (3.8) because it involves Python byte code. That's less scary than it sounds because this test is mostly checking expressions, and changes in expression byte code is minimal. Updating it will be a matter of getting a newer version of [uncompyle6](https://github.com/rocky/python-uncompyle6/) (it now works with Pythons 3.9 and 3.10) and _maybe_ making a small change to the test.

### Steps to Reproduce

Run CI.

### Expected Results

CI should not fail.

### Observed Results

CI failed.

### Relevant log output

https://github.com/scikit-hep/vector/actions/runs/3634233305/jobs/6132119346

```
Run actions/setup-python@v4
  with:
    python-version: [3](https://github.com/scikit-hep/vector/actions/runs/3634233305/jobs/6132119346#step:3:3).8.8
    check-latest: false
    token: ***
    update-environment: true
Version 3.8.8 was not found in the local cache
Error: Version 3.8.8 with arch x6[4](https://github.com/scikit-hep/vector/actions/runs/3634233305/jobs/6132119346#step:3:4) not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

**Comment by Saransh-cpp** [comment]
Vector is currently only tested on awkward v1's `._v2`.

A PR is open for `v2` support (reviewed by @agoose77!) - #284. I re-ran the tests on this PR and they pass with `rc6` - https://github.com/scikit-hep/vector/actions/runs/3506891827/jobs/6138148137.

I wanted to discuss a couple of points before merging the `v2` support PR - https://github.com/scikit-hep/vector/pull/284#issuecomment-1323399760.

Also, I see the issue template has some redundant fields. I'll trim it down.
