### ISSUE TITLE
Summation of Vectors (defined from px,py,pz,M data)  does not work as expected

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/vector#372]
### Vector Version

1.1.0

### Python Version

3.11

### OS / Environment

Mac OS

### Describe the bug

I had a (I thought) fairly simple use case

* generate events with 10 particles iwth random momenta for particle of known mass 1
* determine the total 4 vector

and I expected this to work

```
p = np.random.uniform(size = (123,10,3))
m = np.zeros((123,10,1))
V = np.concatenate([p,m],axis=-1)

vecs = vector.array({
    'px': V[:,:,0],
    'py': V[:,:,1],
    'pz': V[:,:,2],
    'M': V[:,:,3]
})

vecs.sum(axis=1)
```

but I got this error message

```
File ~/.pyenv/versions/3.11.4/envs/garbargeml/lib/python3.11/site-packages/numpy/core/fromnumeric.py:88, in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     85         else:
     86             return reduction(axis=axis, out=out, **passkwargs)
---> 88 return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

TypeError: 'NoneType' object cannot be interpreted as an integer
```

To me that seems like sth that would be in scope for `vector`

@jpivarski came up with this solution using awkward, but this should not require awkward

```
>>> import awkward as ak, numpy as np
>>> import vector
>>> vector.register_awkward()

>>> p = np.random.uniform(size = (123,10,3))
>>> m = np.zeros((123,10,1))
>>> V = np.concatenate([p,m],axis=-1)

>>> vecs = ak.zip({
...     'px': V[:,:,0],
...     'py': V[:,:,1],
...     'pz': V[:,:,2],
...     'M': V[:,:,3]
... }, with_name="Momentum4D")

>>> ak.sum(vecs, axis=1)
<MomentumArray4D [{t: 7.77, z: 3.4, x: 3.08, ...}, ...] type='123 * Momentu...'>
```

**Comment by Saransh-cpp** [comment]
Hi @lukasheinrich!

`vector.array` is a constructor for `Numpy` type vectors and `vector.Array` is the constructor you are looking for (actually, I think, even this is not the right constructor, but this is the one you were expecting would work (?)).

If you replace `array` with `Array`, you'll get the following (intentional) error -
```py
In [1]: import numpy as np; import vector

In [2]: p = np.random.uniform(size = (123,10,3))
   ...: m = np.zeros((123,10,1))
   ...: V = np.concatenate([p,m],axis=-1)

In [3]: vecs = vector.Array({
   ...:     'px': V[:,:,0],
   ...:     'py': V[:,:,1],
   ...:     'pz': V[:,:,2],
   ...:     'M': V[:,:,3]
   ...: })
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 vecs = vector.Array({
      2     'px': V[:,:,0],
      3     'py': V[:,:,1],
      4     'pz': V[:,:,2],
      5     'M': V[:,:,3]
      6 })

File /opt/homebrew/lib/python3.10/site-packages/vector/backends/awkward_constructors.py:318, in Array(*args, **kwargs)
    315 array_type = akarray.type
    317 if not _is_type_safe(array_type):
--> 318     raise TypeError("a coordinate must be of the type int or float")
    319 fields = awkward.fields(akarray)
    321 is_momentum, dimension, names, arrays = _check_names(akarray, fields)

TypeError: a coordinate must be of the type int or float
```

---

For your use case, you should use `vector.zip`, which works just like `ak.zip` -
```py
In [1]: import numpy as np; import vector; import awkward as ak

In [2]: p = np.random.uniform(size = (123,10,3))
   ...: m = np.zeros((123,10,1))
   ...: V = np.concatenate([p,m],axis=-1)

In [3]: vecs = vector.zip({
   ...:     'px': V[:,:,0],
   ...:     'py': V[:,:,1],
   ...:     'pz': V[:,:,2],
   ...:     'M': V[:,:,3]
   ...: })

In [4]: ak.sum(vecs, axis=1)  # would work
Out[4]: <MomentumArray4D [{t: 8.23, z: 3.65, x: 4.69, ...}, ...] type='123 * Moment...'>
```

I hope this helps! :)

**Comment by Saransh-cpp** [comment]
Oh, I see, thanks for the explanation! (sorry for the late reply)

Vector does have a custom `sum` function and also implements `__array_function__` for `VectorNumpy` classes. I debugged a bit, and the MWE works if you set the keyword argument `keepdims` to `True` or `False`. The `keepdims=None` (default) case is not tested; hence this bug went unnoticed. Digging some more, the default value of `keepdims` in the [definition of `numpy.sum`](https://github.com/numpy/numpy/blob/db4f43983cb938f12c311e1f5b7165e270c393b4/numpy/core/fromnumeric.py#L2177-L2314) is `np._NoValue` (and not `None`). I think updating the default value of `keepdims` in vector should work. I'll create a PR and request your review.
