### ISSUE TITLE
Fix CI badge in README and docs

### ISSUE THREAD

**Issue by Saransh-cpp** [scikit-hep/vector#383]
Currently, the CI badge shows "passing" but the workflows are failing. The badge should be using the following svg - https://github.com/scikit-hep/vector/actions/workflows/ci.yml/badge.svg

**Comment by frantic-rabbit** [comment]
Hey, can i work on this issue?

**Comment by Saransh-cpp** [comment]
Go ahead!

- `index.rst` - https://github.com/scikit-hep/vector/blob/main/docs/index.rst
- `README.md` - https://github.com/scikit-hep/vector/blob/main/README.md

**Comment by Anurag-Nagpal** [comment]
Hey @Saransh-cpp, can you check this Fix CI badge in README and docs #384

**Comment by frantic-rabbit** [comment]
Hey @Saransh-cpp, I have made the required changes. Please review it.
