### ISSUE TITLE
Add missing docstring examples

### ISSUE THREAD

**Issue by Saransh-cpp** [scikit-hep/vector#503]
All the `# TODO: Add an example here - see https://github.com/scikit-hep/vector/issues/194` lines in https://github.com/scikit-hep/vector/blob/main/src/vector/backends/numpy.py

**Comment by pandyah5** [comment]
I can add a few of these docstrings. Will link a PR to the issue when it is ready!

**Comment by pandyah5** [comment]
Hi @Saransh-cpp apologies for the delay. Work kept me busy lately hence the delay. The PR is now up for review, I have tested the demo commands myself and verified them. If there are any changes I should make, feel free to leave a comment on my PR. Have a great weekend :)
