### ISSUE TITLE
mass from `VectorArray4D`?

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/vector#78]
I'm probably missing something basic, but I would have expected something like this to work?

```
import vector as vc
fourvectors = vc.awk([
    [{"px": 1, "py": 1.1, "pz": 0.1, 'e': 3.3}, {"px": 2, "py": 2.2, "pz": 0.2, 'e': 3.3}],
])
fourvectors.mass2
```

I tried `.mass`,`.M2`,`.mass2`,`.M2()` but all end in 

```
  1092                 raise AttributeError(
   1093                     "no field named {0}".format(repr(where))
-> 1094                     + ak._util.exception_suffix(__file__)
   1095                 )
   1096 

AttributeError: no field named 'M2'
```

or similar

what's the right way to do this?

**Comment by lukasheinrich** [comment]
Some more info 

this workss

```
fourvectors = vc.awk([
    [{"x": 1, "y": 1.1, "z": 0.1, 't': 3.3}, {"x": 2, "y": 2.2, "z": 0.2, 't': 3.3}],
])
print(type(fourvectors))
fourvectors.mag2
```

showing the type to be `VectorArray4D` 

while the type of 

```
fourvectors = vc.awk([
    [{"px": 1, "py": 1.1, "pz": 0.1, 'e': 3.3}, {"px": 2, "py": 2.2, "pz": 0.2, 'e': 3.3}],
])
```

is `MomentumArray3D` (3D  not 4D as expected)

**Comment by jpivarski** [comment]
This is definitely a bug:

```python
{"px": 1, "py": 1.1, "pz": 0.1, 'e': 3.3}
```

should make a MomentumArray4D, not 3D and not non-momentum. The fact that it's turning up 3D is why it says there's no mass (or mass2).

**Comment by lukasheinrich** [comment]
aha!

`{"px": 1, "py": 1.1, "pz": 0.1, 'e': 3.3}` does not work, but 

`{"px": 1, "py": 1.1, "pz": 0.1, 'E': 3.3}` does

not sure tthis is a bug or just a choice of capitalization

**Comment by henryiii** [comment]
No, sounds reasonable.

**Comment by lukasheinrich** [comment]
the aux. fields are definitely important (this came up in the context of `pylhe` (and https://github.com/scikit-hep/awkward-1.0/discussions/818) and I did wonder what happens to those under operatoinns like `+`  etc... would the idea be that you have a `vector` property ?

```
{'isolation': 1.23, 'vector': {'px': 1, 'py': 2, 'pz': 3, 'E': 4}, 'grouped_aux': {'charge': 1.0, 'pid': 123}}
```

**Comment by henryiii** [comment]
Could it be a default off option? allow_extra=True?

**Comment by jpivarski** [comment]
It could be a default option, as the function is already written (`vector.awk`). However, but the "containment is more powerful than inheritance" rule, forcing

```
events = ak.Array([{'isolation': 1.23, 'vector': {'px': 1, 'py': 2, 'pz': 3, 'E': 4}, 'grouped_aux': {'charge': 1.0, 'pid': 123}}, ...])
```

or

```
events = ak.Array([{'isolation': 1.23, 'vector': {'px': 1, 'py': 2, 'pz': 3, 'E': 4}, 'charge': 1.0, 'pid': 123}, ...])
```

might be good practice, since `+` will not work on this record structure; it forces users to extract the vectors with `events.vector` before applying `+`, and then they know exactly what's being added. Having all those fields be silently dropped was probably a bad idea. Alternatively requiring `allow_extra=True` also forces users to be aware of what they're doing, but at a different part of the code.

**Comment by lukasheinrich** [comment]
I agree the first one is better as long as it does't incur performace penalties for calculating e.g. mixed quantities things like `events[:].isolation/events[:].vector.E`

does awkward provide  idioms to reshape/restructure easily from one to the other (for the case without behaviors e.g. pure records/arrayswhen initially preparing the data)?

**Comment by jpivarski** [comment]
> I agree the first one is better as long as it does't incur performace penalties for calculating e.g. mixed quantities things like `events[:].isolation/events[:].vector.E` which I believe it doesn't

That is correct. All of the above is just metadata manipulation; the arrays themselves are untouched (passed around by reference).

> does awkward provide idioms to reshape/restructure easily from one to the other (for the case without behaviors e.g. pure records/arrayswhen initially preparing the data)?

Pulling fields out is [projection](https://awkward-array.readthedocs.io/en/latest/_auto/ak.Array.html#projection) (one at a time) or [ak.unzip](https://awkward-array.readthedocs.io/en/latest/_auto/ak.unzip.html) (all at once), and gluing fields together into a record is [ak.zip](https://awkward-array.readthedocs.io/en/latest/_auto/ak.zip.html), which might need `depth_limit=1` to prevent deep broadcasting. Note that [ak.zip](https://awkward-array.readthedocs.io/en/latest/_auto/ak.zip.html) has a `parameters` and a `with_name` (shortcut for `parameters = {"__record__": name}`) argument.

If this is related to scikit-hep/awkward-1.0#818, I think your case is just complex enough that you'd rather use the [ak.ArrayBuilder](https://awkward-array.readthedocs.io/en/latest/_auto/ak.ArrayBuilder.html) method you settled on in the end.

**Comment by jpivarski** [comment]
Actually, it would be difficult to do this, whether gated by `allow_extra=True` or not. Awkward Array doesn't run any hooks at construction-time—if an array of vectors is nested deeply within a structure, there is no Python object associated with it, so "construction-time" doesn't have a clear meaning. (For instance, someone could be using an array containing vectors for a long time before it ever reaches top-level of the data structure and gets instantiated as a Python class. Finding out that it has the wrong set of fields _at that time_ would be pretty surprising.)

The least invasive thing would be to let Awkward Arrays of vectors continue to be loose, as it's the philosophy of Awkward Array that a function can proceed if it has the minimum required set of fields, not if any additional fields are excluded. But the above problem can be addressed by adding lower-case "`e`" and "`m`" as input arguments and output attributes. It would increase some combinatorics, though.
